# Generated by Django 3.1.1 on 2020-10-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='none'),
            preserve_default=False,
        ),
    ]
