# Generated by Django 3.1.1 on 2020-10-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201007_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
