# Generated by Django 3.1.1 on 2020-10-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0002_auto_20201011_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
