# Generated by Django 3.1.1 on 2020-10-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0003_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
    ]
