# Generated by Django 3.1.1 on 2020-10-10 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=150)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_adress', models.CharField(max_length=100, null=True)),
                ('nip_number', models.CharField(max_length=18, null=True)),
                ('regon_number', models.CharField(max_length=22, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
