# Generated by Django 3.1.1 on 2020-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_order'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.Product'),
        ),
    ]
