# Generated by Django 3.1.1 on 2020-10-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201017_0830'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_adress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nip_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='regon_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='bought_products',
            field=models.ManyToManyField(blank=True, to='core.Product'),
        ),
    ]
