# Generated by Django 3.1.1 on 2020-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201017_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('default', 'Default'), ('amelia', 'Amelia'), ('cerulean', 'Cerulean'), ('cosmo', 'Cosmo'), ('cyborg', 'Cyborg'), ('flatly', 'Flatly'), ('journal', 'Journal'), ('readable', 'Readable'), ('simplex', 'Simplex'), ('slate', 'Slate'), ('spacelab', 'SpaceLab'), ('united', 'United'), ('superhero', 'Superhero'), ('lumen', 'Lumen')], default='default', max_length=255)),
            ],
        ),
    ]
