# Generated by Django 3.1.1 on 2020-10-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='items',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shoes',
        ),
    ]
