# Generated by Django 3.1.1 on 2020-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_order'),
        ('accounts', '0003_auto_20201010_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bought_products',
            field=models.ManyToManyField(blank=True, to='core.Product'),
        ),
    ]
