# Generated by Django 3.1.1 on 2020-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_order'),
        ('shopping_cart', '0003_auto_20201010_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.Product'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
