# Generated by Django 3.1.1 on 2020-10-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_auto_20201014_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='user',
        ),
    ]
