# Generated by Django 3.1.1 on 2020-10-18 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0013_auto_20201018_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='[0-9]{2}\\-[0-9]{3}')]),
        ),
    ]
