# Generated by Django 3.1.1 on 2020-10-18 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0015_auto_20201018_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='Nieprawidłowy kod pocztowy', message='Nieprawidłowy kod pocztowy', regex='[0-9]{2}\\-[0-9]{3}')]),
        ),
    ]
